services:
  product_service:
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      product_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - backend_network
    ports:
      - "8001:8001"

  product_db:
    image: "postgres:17"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_PRODUCT_SERVICE_USER}
      POSTGRES_PASSWORD: ${DB_PRODUCT_SERVICE_PASSWORD}
      POSTGRES_DB: ${DB_PRODUCT_SERVICE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_PRODUCT_SERVICE_USER} -d ${DB_PRODUCT_SERVICE_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - product_pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  product_pgdata:
