"""add status

Revision ID: 9fff0f1dfd5a
Revises: 4e470eb889e1
Create Date: 2026-03-19 22:07:46.334951

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9fff0f1dfd5a"
down_revision: Union[str, Sequence[str], None] = "4e470eb889e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE productstatus AS ENUM ('PENDING', 'APPROVED', 'REJECTED')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="productstatus"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "status")
    op.execute("DROP TYPE productstatus")
