"""add field seller_id

Revision ID: 807b6358f872
Revises: 3b8aaf8364fa
Create Date: 2026-03-01 11:29:56.276799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807b6358f872'
down_revision: Union[str, Sequence[str], None] = '3b8aaf8364fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserved_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('seller_id', sa.UUID(), nullable=False))
    op.alter_column('products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default='0.0',
               existing_nullable=False)
    op.alter_column('products', 'total_reviews',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'total_reviews',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_column('products', 'seller_id')
    op.drop_table('reserved_products')
    # ### end Alembic commands ###
