"""remove nullable feilds

Revision ID: ceaa8d9933c0
Revises: 41fa2c779c58
Create Date: 2026-03-03 13:56:49.979205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceaa8d9933c0'
down_revision: Union[str, Sequence[str], None] = '41fa2c779c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'article',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'price_discount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price_discount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'article',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
