"""add total_reviews to product model

Revision ID: 3b8aaf8364fa
Revises: dfcb4c64b3b9
Create Date: 2025-09-07 14:36:23.140007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8aaf8364fa'
down_revision: Union[str, Sequence[str], None] = 'dfcb4c64b3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('total_reviews', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'total_reviews')
    # ### end Alembic commands ###
